// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/contexts": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contexts"
                ],
                "summary": "List kubeconfig contexts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/cluster.ContextInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/deployments/{name}/scale": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Scale a workload (deployments, statefulsets, replicasets)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/jobs/{name}/cancel": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Cancel a Job: suspend it and delete its running pods",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/pods/{name}/log": {
            "get": {
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Stream pod logs (SSE)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/resources/{resource}/watch": {
            "get": {
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "watch"
                ],
                "summary": "Watch resources (SSE)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/resources/{resource}/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Get one resource",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Delete one resource",
                "responses": {}
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Patch one resource (merge patch)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/resources/{resource}/{name}/yaml": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Get one resource as YAML",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/{workload}/{name}/restart": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Rollout restart a workload",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/{workload}/{name}/resume": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Resume a suspended CronJob or Job (sets spec.suspend=false)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/{workload}/{name}/rollout/history": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rollout"
                ],
                "summary": "List rollout revision history for a workload",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/{workload}/{name}/rollout/pause": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rollout"
                ],
                "summary": "Pause a Deployment rollout (sets spec.paused=true)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/{workload}/{name}/rollout/resume": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rollout"
                ],
                "summary": "Resume a paused Deployment rollout (sets spec.paused=false)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/{workload}/{name}/rollout/undo": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rollout"
                ],
                "summary": "Roll back to a previous revision (toRevision=0 means previous)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/{workload}/{name}/scale": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Scale a workload (deployments, statefulsets, replicasets)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/namespaces/{ns}/{workload}/{name}/suspend": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Suspend a CronJob or Job (sets spec.suspend=true)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/nodes/{name}/drain": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "actions"
                ],
                "summary": "Drain a node: cordon + evict non-daemonset pods",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/resources": {
            "post": {
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Apply a YAML manifest (server-side apply)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/resources/{resource}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "List resources (server-side table)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Context name or _current",
                        "name": "ctx",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource (e.g. pods, deployments.apps)",
                        "name": "resource",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handler.TablePayload"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/contexts/{ctx}/resources/{resource}/watch": {
            "get": {
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "watch"
                ],
                "summary": "Watch resources (SSE)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/resources/{resource}/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Get one resource",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Delete one resource",
                "responses": {}
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Patch one resource (merge patch)",
                "responses": {}
            }
        },
        "/api/v1/contexts/{ctx}/resources/{resource}/{name}/yaml": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Get one resource as YAML",
                "responses": {}
            }
        }
    },
    "definitions": {
        "cluster.ContextInfo": {
            "type": "object",
            "properties": {
                "cluster": {
                    "type": "string"
                },
                "isCurrent": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "handler.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "handler.RowObject": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "handler.TableColumn": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "handler.TablePayload": {
            "type": "object",
            "properties": {
                "columns": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.TableColumn"
                    }
                },
                "rows": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.TableRow"
                    }
                }
            }
        },
        "handler.TableRow": {
            "type": "object",
            "properties": {
                "cells": {
                    "type": "array",
                    "items": {}
                },
                "object": {
                    "$ref": "#/definitions/handler.RowObject"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Helmsman API",
	Description:      "Local Kubernetes cluster management API. Connects to whichever cluster your kubeconfig points at.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
